[workspace]
resolver = "2"
members = [
    "oracle",
    "randomness-oracle",
    "randomness-oracle-io",
    "io",
    "roll-dice-example",
    "horse-races"
]

[patch.'https://github.com/gear-tech/gear.git']
gtest = { git = "https://github.com/gear-dapps/gear.git",  rev = "6471eb93" }
gear-wasm-builder = { git = "https://github.com/gear-dapps/gear.git",  rev = "6471eb93" }
gcore = { git = "https://github.com/gear-dapps/gear.git", features = ["debug"], rev = "6471eb93" }
gstd = { git = "https://github.com/gear-dapps/gear.git", features = ["debug"], rev = "6471eb93" }